### ISSUE TITLE
I don't understand how am I supposed to use it

### ISSUE THREAD

**Issue by fiatjaf** [captn3m0/potion#16]
There's no build branch nor build to download from anywhere.
Help me!

**Comment by captn3m0** [comment]
Sorry, but I decided to give up on potion for multiple reasons:

- It wasn't very well organized.
- Ultimately, it was targeted to a very small audience: people who use Jekyll for blogging and want a svbtle-style interface

If you want you can try it locally by cloning it running it on a webserver.

I'll mark the repo as deprecated, but you might be interested in [sazed](http://assembly.com/sazed), which is like a better version of potion. It will be embeddable and drop-able into any jekyll website.

The source code is available as two repos: [sazed](https://github.com/asm-products/sazed) and [sazed-core](https://github.com/asm-products/sazed-core)
